### ISSUE TITLE
Design: UX - Low fidelity Wire Frames

### ISSUE THREAD

**Issue by moakley-45** [moakley-45/Team-Quiz#3]
## Issue overview & User stories:

We need to create wireframes for the site, across Mobile, tablet and Desktop sizes, in deference to the marking criteria:

> Create wireframes for the website's main pages, defining the layout and user flow.

## Acceptance Criteria:
- Mobile wireframe
- Tablet wireframe
- Desktop wireframe

## Work Done:
- [x] Mobile wireframe
- [x] Tablet wireframe
- [x] Desktop wireframe

**Comment by student0Zero** [comment]
[Quiz_Wireframes.pdf](https://github.com/user-attachments/files/17464499/Quiz_Wireframes.pdf)
